#!/usr/bin/env node
/**
 * generate-all.mjs
 * Generates all 100 skeleton HTML files from templates and manifest.
 * Each skeleton is a standalone, single-file HTML page with inline CSS and JS.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const TEMPLATES_DIR = join(ROOT, 'templates');
const MANIFEST_PATH = join(ROOT, 'skeletons-manifest.json');

const manifest = JSON.parse(readFileSync(MANIFEST_PATH, 'utf-8'));

// Generate index-catalog.js from manifest
const catalogData = JSON.stringify(manifest, null, 2);
const catalogJs = readFileSync(join(ROOT, 'index-catalog.js'), 'utf-8')
  .replace('SKELETONS_PLACEHOLDER', catalogData);
writeFileSync(join(ROOT, 'index-catalog.js'), catalogJs);
console.log(`✓ Catalog JS updated with ${manifest.length} entries`);

// Each skeleton gets generated by the sub-agent — this script just ensures
// the catalog JS is up to date and creates placeholder directories
let created = 0;
for (const s of manifest) {
  const dir = join(TEMPLATES_DIR, s.slug);
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
    created++;
  }
}
console.log(`✓ ${created} skeleton directories created (${manifest.length} total)`);

// Generate CATALOG.md
let catalog = '# 📚 Skeleton Catalog\n\n';
catalog += `> ${manifest.length} premium frontend skeletons — each with its own product identity.\n\n`;
catalog += '| # | Name | Category | Use Case | Folder | Screenshot | Design Book |\n';
catalog += '|---|------|----------|----------|--------|------------|-------------|\n';
manifest.forEach((s, i) => {
  catalog += `| ${i+1} | **${s.name}** | ${s.category} | ${s.useCase} | [\`📁\`](./templates/${s.slug}/) | [\`🖼️\`](./templates/${s.slug}/screenshot.png) | [\`📖\`](./templates/${s.slug}/DESIGN_BOOK.md) |\n`;
});
writeFileSync(join(ROOT, 'CATALOG.md'), catalog);
console.log(`✓ CATALOG.md generated`);

console.log(`\nDone! Run 'npm run build' to build, 'npm run dev' to preview.`);
